# This is a basic workflow to help you get started with Actions



name: CHECKALIVE


# Controls when the action will run. Triggers the workflow on push or pull request

# events but only for the master branch

on:

  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:

  # This workflow contains a single job called "build"

  build:

    # The type of runner that the job will run on

    runs-on: ubuntu-18.04


    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - uses: actions/checkout@v2


      - name: Download Tools
        
        continue-on-error: true

        run: GO111MODULE=auto go get -u -v github.com/projectdiscovery/httpx/cmd/httpx

        

      - name: Run Tools
        
        continue-on-error: true

        run: /home/runner/go/bin/httpx -l domains.txt -o alives.txt


      - name: Add & Commit
        
        continue-on-error: true

        uses: EndBug/add-and-commit@v4.4.0
