# This is a basic workflow to help you get started with Actions



name: CHECKALIVE


# Controls when the action will run. Triggers the workflow on push or pull request

# events but only for the master branch

on:


  schedule:
    - cron: '0 10 */2 * *'

  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:

  # This workflow contains a single job called "build"

  build:

    # The type of runner that the job will run on

    runs-on: ubuntu-18.04


    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - uses: actions/checkout@v2


      - name: Download Tools
        
        continue-on-error: true

        run: ./httpx_amd64 -version

        

      - name: Run Tools
        
        continue-on-error: true

        run: ./httpx_amd64 -l domains.txt -o alives_tmp.txt


      - name: Unique A
        
        continue-on-error: true

        run: echo "" > alives.txt

      - name: Unique B
        
        continue-on-error: true

        run: cat alives_tmp.txt | sort -u > alives.txt

      - name: Add & Commit
        
        continue-on-error: true

        uses: EndBug/add-and-commit@v4.4.0
